_BASE_: "Base-PolyRCNN.yaml"
DATALOADER:
  NUM_WORKERS: 1
MODEL:
  WEIGHTS: "models/R-101.pkl"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
  PolyRCNN:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("inria_train",)  # 89280 images in total (outer polys), 10908 images in total (inner polys)
  TEST:  ("inria_val",)
SOLVER:
  STEPS: (60698, 68200)  # 89th epoch
  MAX_ITER: 68201  # 100th epoch
  CHECKPOINT_PERIOD: 682  # save checkpoint per epoch
  IMS_PER_BATCH: 16
TEST:
  EVAL_PERIOD: 1000
INPUT:
  CROP:
    ENABLED: False
  FORMAT: "RGB"